name: Publish Docker image

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker registry
    runs-on: docker
    container:
      image: git.arjix.dev/arjix/runner-image:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: git.arjix.dev
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: git.arjix.dev/arjix/runner-image-arch

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
